version: "3"
services:

  mongodb:
    image: mongo
    networks:
     - mongo-net
    ports:
     - 27017:27017
    environment:
     MONGO_INITDB_ROOT_USERNAME: admin
     MONGO_INITDB_ROOT_PASSWORD: password
  mongo-ex:
    depends_on:
     - mongodb
    image: mongo-express
    networks:
     - mongo-net
    ports:
     - 8081:8081
    restart: always
    environment:
     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
     ME_CONFIG_MONGODB_ADMINPASSWORD: password
     ME_CONFIG_MONGODB_SERVER: mongodb
networks:
  mongo-net:
   driver: bridge
   ipam:
    config:
     - subnet: 180.1.0.0/24
       gateway: 180.1.0.1